### ISSUE TITLE
Odd output

### ISSUE THREAD

**Issue by araikes** [bids-apps/tracula#22]
Hi @fliem,

I was trying out this docker container image. I had previously run Freesurfer's longitudinal pipeline using the BIDS-Apps/Freesurfer image. TRACULA ran without any apparent issue. When I went to visualize the tracts is where it got weird. When I try to overlay the tracts on the MNI152 T1 brain, the tracts are nowhere near it. I'm not sure if this is a "me" issue or an issue with the outputs from the analyses. I'm uploading a screenshot for what I see. The command used to open that in freeview was:

`freeview -v /usr/local/fsl/data/standard/MNI152_T1_1mm_brain.nii.gz -w ${PWD}/*.path.mean.txt`

Please let me know what else might be needed to debug this. Thanks.

![screenshot from 2018-04-30 12-28-40](https://user-images.githubusercontent.com/18663624/39446319-f378aeaa-4c72-11e8-9480-984c82eda8bd.png)

**Comment by fliem** [comment]
Hi,
mhh, looks interesting.

Do you see this only for this subject and session, or also for other data in your study?

How does the merged_avg33_mni_bbr.mgz file in native space look like? (`freeview -tv dpath/merged_avg33_mni_bbr.mgz  -v dmri/dtifit_FA.nii.gz`)

**Comment by araikes** [comment]
I apologize. I should've been more specific. That image is based on the group2_tract_stats folder path mean text files. 

For individual subjects/sessions, the merged_avg33 files appear fine in native space and close to ok (offset but not nearly as dramatically) in MNI152 space.

**Comment by fliem** [comment]
Hi, I wont be able to look into this for the next couple of days. I'll get back to you the week after next. Sorry

**Comment by araikes** [comment]
Not a problem.

**Comment by fliem** [comment]
Hi @araikes.
I just tested this with two datasets, and my images look correct (I am using FreeView 2.0) -- like in the [turorial](http://freesurfer.net/fswiki/FsTutorial/TraculaStatistics?action=AttachFile&do=get&target=path.waypts.jpg).

Does the attached file display correctly? It might be a bit squiggly, because it's only based on two subjects, but the general position and orientation should work.
[lh.cst_AS.avg33_mni_bbr.path.mean.txt](https://github.com/BIDS-Apps/tracula/files/2000512/lh.cst_AS.avg33_mni_bbr.path.mean.txt)

Other than that, I can only point you towards the FS mailing list.
